import java.util.HashMap;
import java.util.Scanner;

/**
 * Drives the order-matching simulation: reads the input header and order
 * stream, validates each order, routes it to the matching {@link Stock},
 * and prints the requested verbose/median/trader-info output.
 *
 * <p>The input format is:
 * <pre>
 * COMMENT: &lt;free text&gt;
 * MODE: TL | PR
 * NUM_TRADERS: &lt;n&gt;
 * NUM_STOCKS: &lt;n&gt;
 * [RANDOM_SEED: &lt;n&gt;]          (PR mode only)
 * [NUMBER_OF_ORDERS: &lt;n&gt;]     (PR mode only)
 * [ARRIVAL_RATE: &lt;n&gt;]         (PR mode only)
 * &lt;timestamp&gt; BUY|SELL T&lt;id&gt; S&lt;id&gt; $&lt;price&gt; #&lt;quantity&gt;
 * ...
 * </pre>
 * In TL ("trade log") mode the orders above are read directly from input.
 * In PR ("pseudo-random") mode they are instead generated by
 * {@link P2Random#PRInit}.
 */
public class StockMarket {
    private final Options options;
    private final HashMap<String, Trader> traders = new HashMap<>();
    private HashMap<String, Stock> stocks;

    private boolean prMode;
    private int numOfTraders;
    private int numOfStocks;
    private int seed;
    private int numberOfOrders;
    private int arrivalRate;

    private int nextOrderId;
    private int ordersProcessed;
    private int time = 0;

    public StockMarket(Options options) {
        this.options = options;
    }

    /**
     * Reads the COMMENT/MODE/NUM_TRADERS/NUM_STOCKS header line-by-line,
     * plus the RANDOM_SEED/NUMBER_OF_ORDERS/ARRIVAL_RATE block when MODE is PR.
     */
    private void header(Scanner scanner) {
        scanner.nextLine();                 // COMMENT: ...
        scanner.next();                     // "MODE:"
        prMode = scanner.next().equals("PR");
        scanner.next();                     // "NUM_TRADERS:"
        numOfTraders = Integer.parseInt(scanner.next());
        scanner.next();                     // "NUM_STOCKS:"
        numOfStocks = Integer.parseInt(scanner.next());
        scanner.nextLine();

        if (prMode) {
            scanner.next();                 // "RANDOM_SEED:"
            seed = Integer.parseInt(scanner.next());
            scanner.next();                 // "NUMBER_OF_ORDERS:"
            numberOfOrders = Integer.parseInt(scanner.next());
            scanner.next();                 // "ARRIVAL_RATE:"
            arrivalRate = Integer.parseInt(scanner.next());
        }
    }

    /**
     * Builds an {@link Order} from a whitespace-split order line, creating
     * the referenced {@link Trader} and {@link Stock} the first time each
     * is seen.
     */
    private Order makeOrder(String[] fields) {
        String traderId = fields[2];
        if (!traders.containsKey(traderId)) {
            traders.put(traderId, new Trader(traderId));
        }

        if (!fields[1].equals("BUY") && !fields[1].equals("SELL")) {
            System.out.println("Invalid Input");
            System.exit(1);
        }

        String stockId = fields[3];
        int price = Integer.parseInt(fields[4].replace("$", ""));
        int quantity = Integer.parseInt(fields[5].replace("#", ""));

        if (!stocks.containsKey(stockId)) {
            stocks.put(stockId, new Stock(stockId));
        }

        int timeStamp = Integer.parseInt(fields[0]);
        if (fields[1].equals("BUY")) {
            return new BuyOrder(timeStamp, traders.get(traderId), stockId, price, quantity, nextOrderId);
        } else {
            return new SellOrder(timeStamp, traders.get(traderId), stockId, price, quantity, nextOrderId);
        }
    }

    /** Exits with an error message if the order violates any input constraint. */
    private void validateOrder(Order order) {
        if (order.getTime() < 0) {
            System.err.println("Cannot look at negative time index");
            System.exit(1);
        }
        if (order.getTraderID() >= numOfTraders || order.getTraderID() < 0) {
            System.err.println("Invalid Trader ID");
            System.exit(1);
        }
        if (order.getStockNum() >= numOfStocks || order.getStockNum() < 0) {
            System.err.println("Stocks are in range from 0 to Number of Stocks(exclusive)");
            System.exit(1);
        }
        if (order.getPrice() <= 0 || order.getQuantity() <= 0) {
            System.err.println("Cannot compute negative prices or quantities");
            System.exit(1);
        }
        if (order.getTime() < time) {
            System.err.println("Cannot move backward in time");
            System.exit(1);
        }
    }

    /** Prints the running median match price for every stock that has traded so far. */
    private void printMedians() {
        for (int i = 0; i < stocks.size(); i++) {
            Stock stock = stocks.get("S" + i);
            if (stock == null) {
                continue;
            }
            if (!Double.isNaN(stock.getRunningMedian())) {
                System.out.printf("Median match price of Stock %s at time %d is $%.0f\n",
                        stock.getStockNumber(), time, Math.floor(stock.getRunningMedian()));
            }
        }
    }

    /**
     * Runs the simulation end-to-end: reads the header, then processes
     * every order in arrival order, matching trades as they become
     * possible and printing whichever combination of verbose/median/
     * trader-info output was requested via {@link Options}.
     */
    public void runSimulation() {
        Scanner scanner = new Scanner(System.in);

        System.out.println("Processing orders...");
        header(scanner);

        if (prMode) {
            scanner = P2Random.PRInit(seed, numOfTraders, numOfStocks, numberOfOrders, arrivalRate);
        }

        stocks = new HashMap<>();

        while (scanner.hasNextLine()) {
            String[] orderFields = scanner.nextLine().split("\\s");
            Order newOrder = makeOrder(orderFields);
            nextOrderId++;
            validateOrder(newOrder);

            // When the simulation clock advances, report medians for the
            // timestamp that just ended before moving on.
            if (time != newOrder.getTime()) {
                if (options.isMedian()) {
                    printMedians();
                }
                time = newOrder.getTime();
            }

            Stock stock = stocks.get(newOrder.getStockID());
            stock.addOrder(newOrder);
            ordersProcessed += stock.processOrders(options);
        }

        if (options.isMedian()) {
            printMedians();
        }

        System.out.println("---End of Day---");
        System.out.println("Orders Processed: " + ordersProcessed);

        if (options.isTraderInfo()) {
            System.out.println("---Trader Info---");
            for (int i = 0; i < traders.size(); i++) {
                String traderId = "T" + i;
                Trader trader = traders.get(traderId);
                System.out.printf("Trader %s bought %d and sold %d for a net transfer of $%d\n",
                        i, trader.getNumberBought(), trader.getNumberSold(), trader.getNetValueTraded());
            }
        }
    }

    public HashMap<String, Stock> getStocks() {
        return stocks;
    }
}
